name: Auto Sync with Upstream

on:
  repository_dispatch:
    types: [sync-upstream]
  schedule:
    # 백업으로 매일 한 번씩도 체크
    - cron: '0 0 * * *'
  workflow_dispatch: # 수동 실행도 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/erica-likelion/team2-fe.git || true
          git remote -v

      - name: Fetch upstream
        run: git fetch upstream

      - name: Check for updates
        id: check
        run: |
          LOCAL=$(git rev-parse HEAD)
          UPSTREAM=$(git rev-parse upstream/main)
          if [ "$LOCAL" != "$UPSTREAM" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "New changes detected in upstream"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No new changes in upstream"
          fi

      - name: Merge upstream changes
        if: steps.check.outputs.changes == 'true'
        run: |
          git checkout main
          git merge upstream/main --no-edit

      - name: Push changes
        if: steps.check.outputs.changes == 'true'
        run: git push origin main
