name: Sync Fork Repository

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 수동 실행도 가능

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    # 원본 리포에서만 실행
    if: github.repository == 'erica-likelion/team2-fe'
    
    steps:
      - name: Sync fork using GitHub API
        run: |
          # GitHub API를 사용해서 포크 리포지토리 동기화
          curl -X POST \
            -H "Authorization: token ${{ secrets.FORK_SYNC_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/pdjdev/team2-fe/merge-upstream \
            -d '{"branch":"main"}'
          echo "✅ Fork repository synced with upstream!"
