name: Trigger Fork Sync

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 수동 실행도 가능

jobs:
  force-sync-fork:
    runs-on: ubuntu-latest
    # 원본 리포에서만 실행
    if: github.repository == 'erica-likelion/team2-fe'
    
    steps:
      - name: Checkout upstream repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Force push to fork repository
        env:
          GITHUB_TOKEN: ${{ secrets.FORK_SYNC_TOKEN }}
        run: |
          # GitHub CLI를 사용한 더 안전한 방법
          git remote add fork https://github.com/pdjdev/team2-fe.git
          git -c credential.helper= -c credential.https://github.com.username=x-access-token -c credential.https://github.com.password=${{ secrets.FORK_SYNC_TOKEN }} push fork main --force
          echo "✅ Fork repository forcefully synced with upstream!"
